export default [
  {
    bg: "#43728D",
    color: "#DBCCCA",
    album: "The Fame",
    year: "2008",
    songs: [
      "Just Dance",
      "Lovegame",
      "Paparazzi",
      "Poker Face",
      "Eh,Eh (Nothing Else I Can Say)",
      "Beautiful,Dirty,Rich",
      "The Fame",
      "Money Honey",
      "Starstruck",
      "Boys Boys Boys",
      "Paper Gangsta",
      "Brown Eyes",
      "I Like it Rough",
      "Summerboy",
    ],
  },
  {
    bg: "#222222",
    color: "#DFDFDF",
    album: "The Fame Monster",
    year: "2009",
    songs: [
      "Bad Romance",
      "Alejandro",
      "Monster",
      "Speechless",
      "Dance in the Dark",
      "Telephone",
      "So Happy I Could Die",
      "Teeth",
    ],
  },
  {
    bg: "#56544C",
    color: "#ACACAC",
    album: "Born This Way",
    year: "2011",
    songs: [
      "Marry the Night",
      "Born this Way",
      "Government Hooker",
      "Judas",
      "Hair",
      "Beautiful,Dirty,Rich",
      "Scheibe",
      "Bloody Mary",
      "Black Jesus + Amen Fashion",
      "Bad Kids",
      "Fashion of his Love",
      "Highway Unicord (Road to Love)",
      "Heavy Metal Lover",
      "Electric Chapel",
      "The Queen",
      "You and I",
      "The Edge of Glory",
    ],
  },
  {
    bg: "#E22695",
    color: "#1F2846",
    album: "Artpop",
    year: "2013",
    songs: [
      "Aura",
      "Lovegame",
      "Paparazzi",
      "Poker Face",
      "Eh,Eh (Nothing Else I Can Say)",
      "Beautiful,Dirty,Rich",
      "The Fame",
      "Money Honey",
      "Starstruck",
      "Boys Boys Boys",
      "Paper Gangsta",
      "Brown Eyes",
      "I Like it Rough",
      "Summerboy",
    ],
  },
  {
    bg: "#806254",
    color: "#B1B7C0",
    album: "Joanne",
    year: "2016",
    songs: [
      "Just Dance",
      "Lovegame",
      "Paparazzi",
      "Poker Face",
      "Eh,Eh (Nothing Else I Can Say)",
      "Beautiful,Dirty,Rich",
      "The Fame",
      "Money Honey",
      "Starstruck",
      "Boys Boys Boys",
      "Paper Gangsta",
      "Brown Eyes",
      "I Like it Rough",
      "Summerboy",
    ],
  },
  {
    bg: "#32292D",
    color: "#C56576",
    album: "Chromatica",
    year: "2020",
    songs: [
      "Just Dance",
      "Lovegame",
      "Paparazzi",
      "Poker Face",
      "Eh,Eh (Nothing Else I Can Say)",
      "Beautiful,Dirty,Rich",
      "The Fame",
      "Money Honey",
      "Starstruck",
      "Boys Boys Boys",
      "Paper Gangsta",
      "Brown Eyes",
      "I Like it Rough",
      "Summerboy",
    ],
  },
];
